In [ ]:
import pandas as pd
import os
import us

In [ ]:
combined_data = pd.read_csv('combined_data.csv')

C:\Users\Matthew.luong\AppData\Local\Temp\ipykernel_15044\3060903943.py:1: DtypeWarning: Columns (0,1,2,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_data = pd.read_csv('combined_data.csv')

In [ ]:
drop_columns = combined_data.columns[12:]

# Drop the columns
combined_data = combined_data.drop(columns=drop_columns)

In [ ]:
combined_data.head()

In [ ]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4585535 entries, 0 to 4585534
Data columns (total 12 columns):
 #   Column                        Dtype
---  ------                        -----
 0   most_recent_observation       object
 1   most_recent_observation_type  object
 2   common_name                   object
 3   scientific_name               object
 4   city                          object
 5   state                         object
 6   longitude_coordinate          float64
 7   latitude_coordinate           float64
 8   address                       object
 9   condition                     object
 10  height_M                      float64
 11  native                        object
dtypes: float64(3), object(9)
memory usage: 419.8+ MB

In [ ]:
# Group by the specified columns and count the occurrences of tree_name
grouped_df = combined_data.groupby(['state', 'common_name','scientific_name']).size().reset_index(name='tree_count')

# rename common_name
grouped_df = grouped_df.rename(columns={'common_name': 'tree_name'})
grouped_df = grouped_df.rename(columns={'scientific_name': 'tree_species'})

In [ ]:
grouped_df['state_code'] = grouped_df['state'].apply(lambda x: us.states.lookup(x).abbr if us.states.lookup(x) else x)

In [ ]:
grouped_df.to_excel('grouped_data.xlsx',index=False)

# Top 5 trees per state data

In [ ]:
# Group by 'state' and get the top 5 'tree_count' values per state
top_5df = grouped_df.groupby('state', group_keys=False).apply(lambda x: x.nlargest(5, 'tree_count'))

In [ ]:
top_5df.to_excel('top5_data.xlsx',index=False)